site_name: Codio
site_url: https://docs.codio.com
site_description: Codio platform documentation
site_author: Codio team

repo_url: https://github.com/codio/codio-docs
edit_uri: ""

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - javscript
        - java
        - python
#    navigation_depth: 1 
#    collapse_navigation: false
#    titles_only: true
#    sticky_navigation: true

nav:
    - Codio: https://www.codio.com
    - Home: index.md

#extra_css:
#     - css/extra.css

markdown_extensions:
    - toc:
        permalink: ÔÉÅ
    - admonition
    - def_list

copyright: Copyright &copy; 2019 Codio Inc.
#google_analytics: ['', 'docs.codio.com']

# use_directory_urls: false

plugins:
    - search
